### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by davidneudorfer** [jwcrawley/uWho#4]
When I try and run on a Mac, clicking open webcam or video file results in:
```
Application Specific Information:
abort() called
terminating with uncaught exception of type cv::Exception: /tmp/opencv20150428-30707-jc4q91/opencv-2.4.11/modules/core/src/matrix.cpp:116: error: (-215) s >= 0 in function setSize
```

**Comment by jwcrawley** [comment]
Sorry, but I will not be able to test on OSX, given I do not have access to a Mac. 

If you'd like to suggest patches, I would be happy to include them.
